# DOCKER-VERSION 0.3.4

#FROM phusion/baseimage:0.9.13

FROM ruski77/nodejs_image:latest

# make sure apt is up to date
#RUN apt-get update

# Install Node.js and npm
#RUN apt-get install -y nodejs npm

# Bundle app source
#COPY . /src

# Install app dependencies
#RUN cd /src; npm install

#EXPOSE  8080

#CMD ["nodejs", "/src/index.js"]
